# Generated by Django 3.1.7 on 2021-06-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
