# Generated by Django 3.1.7 on 2021-06-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
        ('stt_tests', '0006_auto_20210614_2108'),
        ('tts_tests', '0005_auto_20210614_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
