# Generated by Django 3.1.1 on 2020-09-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextKey',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextLanguage',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('pitch', models.FloatField()),
                ('rate', models.FloatField()),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.text')),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.textkey'),
        ),
        migrations.AddField(
            model_name='text',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.textlanguage'),
        ),
        migrations.AlterUniqueTogether(
            name='text',
            unique_together={('key', 'language')},
        ),
    ]
