# Generated by Django 3.1.7 on 2021-06-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
