# Generated by Django 3.1.7 on 2021-06-14 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
        ('tts_tests', '0003_auto_20210614_2109'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ttstest',
            unique_together={('language', 'text2', 'volume', 'pitch', 'rate')},
        ),
        migrations.RemoveField(
            model_name='ttstest',
            name='text',
        ),
    ]
