# Generated by Django 3.1.7 on 2021-06-14 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
        ('tts_tests', '0004_auto_20210614_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ttstest',
            old_name='text2',
            new_name='text',
        ),
        migrations.AlterUniqueTogether(
            name='ttstest',
            unique_together={('language', 'text', 'volume', 'pitch', 'rate')},
        ),
    ]
