# Generated by Django 3.1.1 on 2021-03-21 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stt_tests', '0001_initial'),
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stttestresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stttest',
            name='text',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='texts.text'),
        ),
    ]
