# Generated by Django 3.1.7 on 2021-06-14 20:50

from django.db import migrations, models

def set_defaults(apps, schema_editor):
    SttTest = apps.get_model('stt_tests', 'SttTest')
    for stt_test in SttTest.objects.all().iterator():
        stt_test.text2 = stt_test.text.text
        stt_test.save()

class Migration(migrations.Migration):

    dependencies = [
        ('stt_tests', '0002_auto_20210321_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='stttest',
            name='text2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RunPython(set_defaults, migrations.RunPython.noop)
    ]
