# Generated by Django 3.1.7 on 2021-06-14 20:55

from django.db import migrations, models
import django.db.models.deletion


def set_defaults(apps, schema_editor):
    SttTest = apps.get_model('stt_tests', 'SttTest')
    for stt_test in SttTest.objects.all().iterator():
        stt_test.language = stt_test.text.language
        stt_test.save()


class Migration(migrations.Migration):
    dependencies = [
        ('texts', '0001_initial'),
        ('stt_tests', '0003_stttest_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='stttest',
            name='language',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='texts.textlanguage',
                                    null=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='stttest',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='texts.textlanguage'),
            preserve_default=False,
        )
    ]
