# Generated by Django 3.1.7 on 2021-06-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
        ('stt_tests', '0005_remove_stttest_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stttest',
            old_name='text2',
            new_name='text',
        ),
        migrations.AlterUniqueTogether(
            name='stttest',
            unique_together={('language', 'text')},
        ),
    ]
